[package]
name = "lineal"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "example"
path = "./example/example_pause.rs"

[dependencies]
perf-event-open-sys2 = "5.0.5"
bitflags = "2.5.0"
libc = "0.2.155"
